# Generated by Django 4.1.5 on 2023-01-31 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guestlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('plus_one', models.CharField(max_length=50)),
                ('rsvp', models.BooleanField(null=True)),
            ],
        ),
    ]
