# Generated by Django 4.1.5 on 2023-02-05 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0003_cuisine'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song_choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('musician', models.CharField(max_length=50)),
                ('guestlist', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='registry.guestlist')),
            ],
        ),
    ]
